# Generated by Django 4.2.6 on 2023-10-17 11:56

import apps.wallets.models.wallet
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='group',
            field=models.ForeignKey(default=apps.wallets.models.wallet.default_group, on_delete=django.db.models.deletion.CASCADE, to='wallets.walletgroup'),
        ),
    ]
