# Generated by Django 4.2.6 on 2023-10-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='color',
            field=models.CharField(default='#ffa000', max_length=9),
        ),
        migrations.AddField(
            model_name='wallet',
            name='icon',
            field=models.CharField(default='radio-button-off-outline', max_length=50),
        ),
    ]
