# Generated by Django 4.2.6 on 2023-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='color',
            field=models.CharField(default='#ffa000', max_length=9),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='icon',
            field=models.CharField(default='radio-button-off-outline', max_length=50),
        ),
    ]
